```{r}
library("modelr")
library("tidyverse")
```

```{r}
library("gapminder")
gapminder::gapminder
```

```{r}
gapminder::gapminder %>% 
  ggplot2::ggplot(aes(year, lifeExp, group = country)) +
    ggplot2::geom_line(alpha = 1/3)
```

```{r}
nz <- dplyr::filter(gapminder::gapminder, country == "New Zealand")
nz %>% 
  ggplot2::ggplot(aes(year, lifeExp)) + 
  ggplot2::geom_line() +
  ggplot2::ggtitle("Full data = ")

nz_mod <- stats::lm(lifeExp ~ year, data = nz)
nz %>% 
  modelr::add_predictions(nz_mod) %>% 
  ggplot2::ggplot(aes(year, pred)) +
  ggplot2::geom_line() +
  ggplot2::ggtitle("Linear trend + ")

nz %>% 
  modelr::add_residuals(nz_mod) %>% 
  ggplot2::ggplot(aes(year, resid)) + 
  ggplot2::geom_hline(yintercept = 0, colour = "white", size = 3) +
  ggplot2::geom_line() +
  ggplot2::ggtitle("Remaining pattern")
```

```{r}
by_country <- gapminder::gapminder %>% 
  dplyr::group_by(country, continent) %>% 
  tidyr::nest()

by_country
```


```{r}
by_country$data[[1]]
```


```{r}
country_model <- function(df) {
  stats::lm(lifeExp ~ year, data = df)
}
```


```{r}
models <- purrr::map(by_country$data, country_model)
```


```{r}
by_country <- by_country %>% 
  dplyr::mutate(model = purrr::map(data, country_model))
by_country
```


```{r}
by_country %>% 
  dplyr::filter(continent == "Europe")
```
```{r}
by_country %>% 
  dplyr::arrange(continent, country)
```


```{r}
by_country <- by_country %>% 
  dplyr::mutate(
    resids = purrr::map2(data, model, add_residuals)
  )
by_country
```


```{r}
resids <- tidyr::unnest(by_country, resids)
resids
```


```{r}
resids %>% 
  ggplot2::ggplot(aes(year, resid)) +
  ggplot2::geom_line(aes(group = country), alpha = 1 / 3) + 
  ggplot2::geom_smooth(se = FALSE)
```


```{r}
resids %>% 
  ggplot2::ggplot(aes(year, resid, group = country)) + 
  ggplot2::geom_line(alpha = 1 / 3) +
  ggplot2::facet_wrap(~continent)
```


```{r}
broom::glance(nz_mod)
```


```{r}
by_country %>% 
  dplyr::mutate(glance = map(model, broom::glance)) %>% 
  tidyr::unnest(glance)
```


```{r}
glance <- by_country %>% 
  dplyr::mutate(glance = map(model, broom::glance)) %>% 
  tidyr::unnest(glance, .drop = TRUE)
glance
```


```{r}
glance %>%  
  dplyr::arrange(r.squared)
```
```{r}
glance %>% 
  ggplot2::ggplot(aes(continent, r.squared)) +
  ggplot2::geom_jitter(width = 0.5)
```


```{r}
bad_fit <- dplyr::filter(glance, r.squared < 0.25)

gapminder %>% 
  dplyr::semi_join(bad_fit, by = "country") %>% 
  ggplot2::ggplot(aes(year, lifeExp, colour = country)) +
  ggplot2::geom_line()
```


```{r}
data.frame(x = list(1:3, 3:5))
```


```{r}
data.frame(
  x = I(list(1:3, 3:5)),
  y = c("1, 2", "3, 4, 5")
)
```


```{r}
tibble::tibble(
  x = list(1:3, 3:5),
  y = c("1, 2", "3, 4, 5")
)
```
```{r}
dplyr::tribble(
   ~x, ~y,
  1:3, "1, 2",
  3:5, "3, 4, 5"
)
```


```{r}
gapminder::gapminder %>% 
  dplyr::group_by(country, continent) %>% 
  tidyr::nest()
```


```{r}
gapminder::gapminder %>% 
  tidyr::nest(data = c(year:gdpPercap))
```


```{r}
df <- dplyr::tribble(
  ~x1,
  "a,b,c", 
  "d,e,f,g"
) 

df %>% 
  dplyr::mutate(x2 = stringr::str_split(x1, ","))
```


```{r}
df %>% 
  dplyr::mutate(x2 = stringr::str_split(x1, ",")) %>% 
  tidyr::unnest(x2)
```

```{r}
sim <- dplyr::tribble(
  ~f,      ~params,
  "runif", list(min = -1, max = 1),
  "rnorm", list(sd = 5),
  "rpois", list(lambda = 10)
)

sim %>%
  dplyr::mutate(sims = invoke_map(f, params, n = 10))
```


```{r}
mtcars %>% 
  dplyr::group_by(cyl) %>% 
  summarise(q = quantile(mpg))
```


```{r}
mtcars %>% 
  dplyr::group_by(cyl) %>% 
  summarise(q = list(quantile(mpg)))
```


```{r}
probs <- c(0.01, 0.25, 0.5, 0.75, 0.99)
mtcars %>% 
  dplyr::group_by(cyl) %>% 
  summarise(p = list(probs), q = list(quantile(mpg, probs))) %>% 
  tidyr::unnest(c(p, q))
```


```{r}
x <- list(
  a = 1:5,
  b = 3:4, 
  c = 5:6
) 

df <- tibble::enframe(x)
df
```


```{r}
df %>% 
  dplyr::mutate(
    smry = purrr::map2_chr(name, value, ~ stringr::str_c(.x, ": ", .y[1]))
  )
```


```{r}
df <- dplyr::tribble(
  ~x,
  letters[1:5],
  1:3,
  runif(5)
)
  
df %>% dplyr::mutate(
  type = map_chr(x, typeof),
  length = map_int(x, length)
)
```


```{r}
df <- dplyr::tribble(
  ~x,
  list(a = 1, b = 2),
  list(a = 2, c = 4)
)
df %>% dplyr::mutate(
  a = map_dbl(x, "a"),
  b = map_dbl(x, "b", .null = NA_real_)
)
```


```{r}
tibble::tibble(x = 1:2, y = list(1:4, 1)) %>% tidyr::unnest(y)
```


```{r}
df1 <- dplyr::tribble(
  ~x, ~y,           ~z,
   1, c("a", "b"), 1:2,
   2, "c",           3
)
df1
```
```{r}
df1 %>% tidyr::unnest(c(y, z))
```


```{r}
# Doesn't work because y and z have different number of elements
df2 <- dplyr::tribble(
  ~x, ~y,           ~z,
   1, "a",         1:2,  
   2, c("b", "c"),   3
)
df2
```


```{r}
df2 %>% tidyr::unnest(c(y, z))
```

